In [4]:
class Car:
    def __init__(self, color, model, year):
        self.color = color
        self.model = model
        self.year = year
    
    def start_engine(self):
        print("Engine started.")
    
    def drive(self, distance):
        print(f"The {self.model} is driving {distance} miles.")
    
    def stop_engine(self):
        print("Engine stopped.")



In [5]:
print(Car)

<class '__main__.Car'>


In [1]:
import numpy as np

In [2]:
array = np.random.random((100,6))

#array

#create a new array where: select all rows from the 2nd column from the above array

In [3]:
array

array([[0.60081408, 0.4074434 , 0.41740476, 0.93935832, 0.99240911,
        0.15176577],
       [0.17367261, 0.56296859, 0.43527969, 0.15793559, 0.5553216 ,
        0.89758101],
       [0.32487488, 0.76667409, 0.91265238, 0.85072777, 0.0172226 ,
        0.88558667],
       [0.29415318, 0.54318049, 0.70094913, 0.41296942, 0.6973248 ,
        0.48783763],
       [0.954982  , 0.53732221, 0.05400811, 0.06596126, 0.57120154,
        0.27581794],
       [0.28417604, 0.16187078, 0.0829414 , 0.02291802, 0.21230575,
        0.13397704],
       [0.61700961, 0.38706494, 0.20119234, 0.44635986, 0.54559838,
        0.76639913],
       [0.98013879, 0.90282135, 0.85586254, 0.03224175, 0.21086016,
        0.00913908],
       [0.99764239, 0.24959086, 0.84784935, 0.71262009, 0.25805155,
        0.19815043],
       [0.78660376, 0.2975704 , 0.62168739, 0.84367077, 0.52716673,
        0.34851023],
       [0.02771863, 0.25584816, 0.47354215, 0.77527829, 0.97995278,
        0.14105698],
       [0.99647507, 0

In [4]:
column2_array = array[:,1]


In [11]:
column2_array

array([0.4074434 , 0.56296859, 0.76667409, 0.54318049, 0.53732221,
       0.16187078, 0.38706494, 0.90282135, 0.24959086, 0.2975704 ,
       0.25584816, 0.06929305, 0.59215016, 0.48170058, 0.96736578,
       0.77751459, 0.78341548, 0.5674062 , 0.83117608, 0.35448634,
       0.0119589 , 0.73334981, 0.19835727, 0.90211619, 0.31626817,
       0.23450219, 0.26170082, 0.5916073 , 0.37524718, 0.03650127,
       0.78215907, 0.6246595 , 0.66975807, 0.08491842, 0.21071281,
       0.10866445, 0.06506244, 0.37030375, 0.19231723, 0.43090769,
       0.03320156, 0.39833011, 0.23179448, 0.30453009, 0.187437  ,
       0.2255184 , 0.58429128, 0.77107516, 0.19736373, 0.1225001 ,
       0.40944435, 0.10254288, 0.55801924, 0.56153353, 0.25193309,
       0.86324533, 0.69730978, 0.86384838, 0.11728538, 0.6984638 ,
       0.61061597, 0.10794889, 0.1822142 , 0.6979293 , 0.81211388,
       0.12428245, 0.10045381, 0.61480912, 0.88779609, 0.14954052,
       0.69480083, 0.18713677, 0.34799626, 0.90630358, 0.54557

In [13]:
#select all rows from the 5th column from the above array

column5_array = column2_array[:,4]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [7]:
column5_array

array([[0.99240911, 0.15176577],
       [0.5553216 , 0.89758101],
       [0.0172226 , 0.88558667],
       [0.6973248 , 0.48783763],
       [0.57120154, 0.27581794],
       [0.21230575, 0.13397704],
       [0.54559838, 0.76639913],
       [0.21086016, 0.00913908],
       [0.25805155, 0.19815043],
       [0.52716673, 0.34851023],
       [0.97995278, 0.14105698],
       [0.30904462, 0.78117974],
       [0.16017653, 0.49564895],
       [0.13161888, 0.03779064],
       [0.58115234, 0.09826466],
       [0.49306334, 0.28541447],
       [0.92199851, 0.53538658],
       [0.58078186, 0.20989896],
       [0.81588283, 0.22419349],
       [0.63461758, 0.15127644],
       [0.62337384, 0.55757033],
       [0.95249832, 0.31732384],
       [0.31079114, 0.17167608],
       [0.15428573, 0.47759331],
       [0.74688021, 0.24820494],
       [0.64760786, 0.50213211],
       [0.75070493, 0.13224611],
       [0.39503542, 0.55816847],
       [0.23021064, 0.77815667],
       [0.21701427, 0.53883908],
       [0.

In [14]:
#select 5 elements starting with the element in the 10th ID from array

five_elements = array[10:15]


In [15]:
five_elements


array([[0.02771863, 0.25584816, 0.47354215, 0.77527829, 0.97995278,
        0.14105698],
       [0.99647507, 0.06929305, 0.75932338, 0.28133946, 0.30904462,
        0.78117974],
       [0.89958833, 0.59215016, 0.83874962, 0.26987766, 0.16017653,
        0.49564895],
       [0.92519204, 0.48170058, 0.95995105, 0.24787911, 0.13161888,
        0.03779064],
       [0.51156935, 0.96736578, 0.71316776, 0.95966008, 0.58115234,
        0.09826466]])

In [ ]:
#create an array from #1 that contains the first rows 50-100 inclusive, but even rows only.

even_rows = array[50:101:2]

In [16]:
set_seed = 42

tree_ID = np.random.randint(0,100,size = (50,10))

block_ID = np.random.randint(0,100,size = (50,10))

tree_diameter = np.random.random((50,10))

stump_diameter = np.random.random((50,10))

tree_data = np.array([[tree_ID],[block_ID],[tree_diameter],[stump_diameter]])


In [26]:
#create an array which contains row data of tree Diameter of 65 of the tree data

tree_diameter_65 = tree_data[2 == 65]
tree_diameter_65

array([], shape=(0, 4, 1, 50, 10), dtype=float64)

In [27]:
b = tree_data[(tree_data[:,2]>65)]

b

IndexError: index 2 is out of bounds for axis 1 with size 1

In [32]:
# Create and print a 1D array called trunk_stump_diameters, which replaces a tree's trunk diameter with its stump diameter if the trunk diameter is zero.
trunk_stump_diameters = np.where(tree_data[:,2] == 0, tree_data[:,3], tree_data[:,2])

SyntaxError: invalid syntax (1059183171.py, line 2)

[Udacity's home page](https://www.udacity.com)

### Italic:

*Hello*
_Hello_

`string.punctuation`

### Bold:

**Hello**
__Hello**

### Code Block

```
import requests
response = requests.get('https://www.udacity.com')
```

    import requests
    response = requests.get('https://www.udacity.com')
    
    
### Math Expression

$$
y = \frac{a}{b+c}
$$


**_must_**

\* for certain very small values of awesome

The sky above the port was the color of television, tuned to a dead channel.  
It was a bright cold day in April, and the clocks were striking thirteen.



I have eaten\
the plums\
that were in\
the icebox

### Blockquote:

The quote: 
>Somewhere, something incredible is waiting to be known 

has been ascribed to Carl Sagan.

My favorite Miss Manners quotes:

>Allowing an unimportant mistake to pass without comment is a wonderful social grace.
>
>Ideological differences are no excuse for rudeness.


### Lists:

Unordered lists can use either asterisks *, plus +, or hyphens - as list markers.
Ordered lists use numbers followed by period . or right paren ).



In [9]:
# Why use NumPy?
import time
import numpy as np
x = np.random.random(100000000)

In [3]:
# Case 1
start = time.time()
sum(x) / len(x)
print(time.time() - start)

5.946194171905518


In [4]:
# Case 2
start = time.time()
np.mean(x)
print(time.time() - start)

0.11929059028625488


In [5]:
x.dtype

dtype('float64')

In [7]:
x.shape

(100000000,)

In [10]:
## We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

## Let's print the ndarray we just created using the print() command
print('x = ', x)

x =  [1 2 3 4 5]


In [12]:
x.ndim

1

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [14]:
arr.ndim

2

In [15]:
x = np.random.random(100000000)

In [16]:
x.ndim

1

In [18]:
## 1-D array
x = np.array([1, 2, 3])
x.ndim

1

In [19]:
## 2-D array
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
Y.ndim

2

In [20]:
## Here the`zeros()` is an inbuilt function that you'll study on the next page. 
## The tuple (2, 3, 4( passed as an argument represents the shape of the ndarray
y = np.zeros((2, 3, 4))
y.ndim

3

In [21]:
print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [22]:
## We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

## We print information about x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]
x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [23]:
## We create a rank 1 ndarray that only contains strings
x = np.array(['Hello', 'World'])

## We print information about x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['Hello' 'World']
x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


In [24]:
## We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

## We print information about x
print('x = ', x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  ['1' '2' 'World']
x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U11


In [25]:
## We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

## We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

## We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

## We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)


The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


In [26]:
## We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

print('Y = \n', Y)

## We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


In [27]:
## We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

## We save x into the current directory as 
np.save('my_array', x)

In [28]:
x

array([1, 2, 3, 4, 5])

In [29]:
## We load the saved array from our current directory into variable y
y = np.load('my_array.npy')

## We print y
print()
print('y = ', y)
print()

## We print information about the ndarray we loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)


y =  [1 2 3 4 5]

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


In [1]:
import plotly.express as px